### ISSUE TITLE
buildingId <a https://airef.github.io/resources/tables/objects.html>

### ISSUE THREAD

**Issue by BYaoKnight** [airef/airef.github.io#1]
when at: 
 - https://airef.github.io/parameters/parameters-details.html#BuildingId
clicking on:
- <a href=...>Objects Table</a>
leads to:
- https://airef.github.io/resources/tables/objects.html , which doesn't exist, but https://airef.github.io/tables/objects.html does

**Comment by airef** [comment]
Thanks for reporting this issue. This is now fixed.
